version: "3"

networks:
  full-stack-networks:

services:
  nginx:
    build: ./deploy
    container_name: nginx
    ports:
      - "8080:80"
#    depends_on:
#      - php
#    volumes:
#      - ./api:/var/www/html
#      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - full-stack-networks

  api:
    build: ./api
    container_name: php
    ports:
      - "8000:8000"