version: "3"

networks:
  full-stack-networks:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./api:/var/www/html
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - full-stack-networks

  php:
    build: ./api
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/html
    networks:
      - full-stack-networks