version: "3"

networks:
  full-stack-networks:

services:
  api:
    image: nginx:latest
    container_name: api
    volumes:
      - ./api/server:/var/www/html
      - ./api/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "9001:9000"
    networks:
      - full-stack-networks

  php:
    build: api
    container_name: php
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    volumes:
      - ./api/server:/var/www/html
    networks:
      - full-stack-networks

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    volumes:
      - /app/node_modules
    networks:
      - full-stack-networks

  nginx:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - client
    networks:
      - full-stack-networks

  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-partaudit}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - full-stack-networks

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=partaudit@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=7BixyPr25B28s7SQ
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - full-stack-networks

  minio:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: minio
    environment:
      MINIO_ROOT_USER: access1234
      MINIO_ROOT_PASSWORD: secret1234
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - full-stack-networks

volumes:
  db-data:
  pgadmin: