import React, { useState } from 'react';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import DivInput from './DivInput';
import { IoIosLock, IoIosPhonePortrait, IoMdMail } from 'react-icons/io';
import { Button } from './Button';
import Link from 'next/link';
import styled from 'styled-components';

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  background: ${(props) => props.theme.color['background']};
  height: 100vh;
  width: 100%;

  .ou {
    font-size: 17px;
    font-weight: 500;
    margin: 10px 0;
  }
`;

const CommonCard = () => {
  return `
      display: flex;
      align-items: center;
      flex-direction: column;
      background: #ffffff;
      border-radius: 8px;
      box-shadow: rgba(99, 99, 99, 0.2) 0 2px 8px 0;
      max-width: 500px;
      width: 100%;
      padding: 13px;
      transition: all ease-in-out 0.5s;
      .button-container {
        width: 310px;
      }
    `;
};

const LoginCard = styled.div`
  ${CommonCard};
  margin-top: 40px;
  height: ${(props) => (!props.registerForm ? '370px' : '100px')};

  .form {
    margin-top: 13px;
  }

  .forget-password {
    margin-top: 30px;
    font-weight: 500;
    text-decoration: underline;
  }
`;

const NewAccount = styled.div`
  ${CommonCard};
  margin-top: 10px;
  height: ${(props) => (props.registerForm ? '390px' : '110px')};
  font-weight: 700;

  div {
    margin-top: 10px;
  }
`;

const InputCheckBox = styled.div`
  display: flex;
  justify-content: center;
  align-self: self-start;
  align-items: center;
  margin-left: 18px;
  margin-top: 5px;
  margin-bottom: 25px;
  font-size: 17px;
`;

const Hidden = styled.div`
  overflow: hidden;
  display: flex;
  flex-direction: column;
  text-align: center;
  text-align: -webkit-center;
  width: 100%;

  label {
    padding-left: 10px;
    font-weight: 300;
  }
`;

const Login = (): JSX.Element => {
  const [registerForm, setRegisterForm] = useState<boolean>(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Mon compte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <LoginCard registerForm={registerForm}>
          <h3>Vous avez déjà un compte PartAudit ?</h3>
          <Hidden>
            <div className="form">
              <DivInput placeholder="Adresse email" type="text">
                <IoMdMail size="1.5em" color="grey" />
              </DivInput>
              <DivInput placeholder="Adresse email" type="password">
                <IoIosLock size="1.8em" color="grey" />
              </DivInput>
            </div>
            <InputCheckBox>
              <input type="checkbox" id="rememberme" />
              <label htmlFor="rememberme">Se souvenir de moi</label>
            </InputCheckBox>
          </Hidden>
          <div className="button-container">
            <Button
              color="blueNight"
              width="410px"
              onClick={() => {
                setRegisterForm(false);
              }}
            >
              <Link href="#">
                <a>Se connecter</a>
              </Link>
            </Button>
          </div>
          {!registerForm && (
            <div className="forget-password">
              <Link href="#">
                <a>Mot de passe oublié ?</a>
              </Link>
            </div>
          )}
        </LoginCard>
        <div className="ou">
          <span>Ou</span>
        </div>
        <NewAccount registerForm={registerForm}>
          <h3>Nouveau sur PartAudit ?</h3>
          <Hidden>
            <div className="form">
              <DivInput placeholder="Numero de telephone" type="text">
                <IoIosPhonePortrait size="1.5em" color="grey" />
              </DivInput>
              <DivInput placeholder="Adresse email" type="text">
                <IoMdMail size="1.5em" color="grey" />
              </DivInput>
              <DivInput placeholder="Mot de passe" type="password">
                <IoIosLock size="1.8em" color="grey" />
              </DivInput>
            </div>
            <InputCheckBox>
              <input type="checkbox" id="acceptsConditions" />
              <label htmlFor="acceptsConditions">
                J&#8217;accepte les CGU de PartAudit
              </label>
            </InputCheckBox>
          </Hidden>
          <div className="button-container">
            <Button
              color="blueNight"
              width="410px"
              onClick={() => {
                setRegisterForm(true);
              }}
            >
              <a>S&#8217;incrire</a>
            </Button>
          </div>
        </NewAccount>
      </Container>
    </div>
  );
};

export default Login;
