FROM php:8.1.4-fpm as build_php

RUN apt-get update && apt-get install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip

RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql

RUN git config --global user.email "example@example.fr" \
    &&  git config --global user.name "username"

WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony

ENTRYPOINT ["docker-entrypoint"]
CMD ["php-fpm"]

FROM nginx
COPY ./api/nginx/default.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www/html/public
EXPOSE 9000